export const SET_SEARCH_FIELD = 'SET_SEARCH_FIELD'

export const GET_ROBOTS = 'GET_ROBOTS'
export const GET_ROBOTS_PROGRESS = 'GET_ROBOTS_PROGRESS'
export const GET_ROBOTS_SUCCESS = 'GET_ROBOTS_SUCCESS'
export const GET_ROBOTS_FAIL = 'GET_ROBOTS_FAIL'